import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productName:"Acqua-di-Gio-Essenza- 150ml (MEN)",
    qunatity:"150 ml",
    brand:"Armani",
    rating:"4.5",
    isRatingGood:true,
    originalPrice:"1300",
    sellingPrice:"999",
    discountOffer:"40% off",
    isSoldOut:true,
    fastDelivery:false,
    image:".assets/MEN/Acqua-di-Gio-Essenza-Giorgio-Armani_men.jpg",
    categoryName: "Men",
  },
  {
   _id: uuid(),
    productName:"Allure-Homme-Sport-Chanel - 100ml (MEN)",
    qunatity:"100 ml",
    brand:"Chanel",
    rating:"3.5",
    isRatingGood:false,
    originalPrice:"1500",
    sellingPrice:"1000",
    discountOffer:"20% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/MEN/Allure-Homme-Sport_chanel-men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Armani-prive-cuir- 100ml (MEN)",
    qunatity:"100 ml",
    brand:"Armani",
    rating:"3.8",
    isRatingGood:false,
    originalPrice:"1800",
    sellingPrice:"1200",
    discountOffer:"30% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/MEN/armani-prive-cuir_men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Armani-Royal_Oud- 150ml (MEN)",
    qunatity:"150 ml",
    brand:"Armani",
    rating:"4",
    isRatingGood:true,
    originalPrice:"3000",
    sellingPrice:"2000",
    discountOffer:"15% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/MEN/Armani-Royal-Oud_men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Armani-sundigioia- 150ml (MEN)",
    qunatity:"150 ml",
    brand:"Armani",
    rating:"4.5",
    isRatingGood:true,
    originalPrice:"4000",
    sellingPrice:"2000",
    discountOffer:"50% off",
    isSoldOut:false,
    fastDelivery:false,
    image:".assets/MEN/armanisundigioia_men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Chanel-paris-1957-150ml (MEN)",
    qunatity:"150 ml",
    brand:"Chanel",
    rating:"4.6",
    isRatingGood:true,
    originalPrice:"13000",
    sellingPrice:"10000",
    discountOffer:"20% off",
    isSoldOut:true,
    fastDelivery:false,
    image:".assets/MEN/chanel-paris-men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Chanel-platinum-egoiste- 150ml (MEN)",
    qunatity:"150 ml",
    brand:"Chanel",
    rating:"4.8",
    isRatingGood:true,
    originalPrice:"3000",
    sellingPrice:"1799",
    discountOffer:"30% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/MEN/chanel-platinum-egoiste_men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Gucci-IntenseOud-UseMe-100ml (MEN)",
    qunatity:"100 ml",
    brand:"Gucci",
    rating:"4.9",
    isRatingGood:true,
    originalPrice:"3000",
    sellingPrice:"899",
    discountOffer:"60% off",
    isSoldOut:true,
    fastDelivery:false,
    image:".assets/MEN/Gucci-IntenseOud-UseMe_men.png",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Gucci-oriental-base- 150ml (MEN)",
    qunatity:"150 ml",
    brand:"Gucci",
    rating:"3.9",
    isRatingGood:true,
    originalPrice:"4000",
    sellingPrice:"1399",
    discountOffer:"40% off",
    isSoldOut:false,
    fastDelivery:false,
    image:".assets/MEN/gucci-oud_men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Zara-nuit-EAU-DE- 150ml (MEN)",
    qunatity:"150 ml",
    brand:"Zara",
    rating:"2.7",
    isRatingGood:false,
    originalPrice:"2000",
    sellingPrice:"1599",
    discountOffer:"10% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/MEN/zara-nuit-men.jpg",
    categoryName: "Men",
  },
  {
    _id: uuid(),
    productName:"Giorgio Armani Si Edp 150ml (WOMEN)",
    qunatity:"150 ml",
    brand:"Armani",
    rating:"3.8",
    isRatingGood:false,
    originalPrice:"7600",
    sellingPrice:"4000",
    discountOffer:"30% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/WOMEN/Armani-Si_women.jpg",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    productName:"Giorgio Armani Si Edp 150ml (WOMEN)",
    qunatity:"150 ml",
    brand:"Armani",
    rating:"4",
    isRatingGood:true,
    originalPrice:"7000",
    sellingPrice:"2599",
    discountOffer:"20% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/WOMEN/ArmaniSIFioriforWomen.jpg",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    productName:"Modern-muse-estee-lauder- 150ml (WOMEN)",
    qunatity:"150 ml",
    brand:"Estee Lauder",
    rating:"3.1",
    isRatingGood:false,
    originalPrice:"1000",
    sellingPrice:"799",
    discountOffer:"40% off",
    isSoldOut:false,
    fastDelivery:false,
    image:".assets/WOMEN/MODERN-MUSE-ESTEE-LAUDER-women.jpg",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    productName:"Estee-Lauder-Pleasures-100ml (WOMEN)",
    qunatity:"100 ml",
    brand:"Estee Lauder",
    rating:"4",
    isRatingGood:true,
    originalPrice:"5000",
    sellingPrice:"1599",
    discountOffer:"40% off",
    isSoldOut:true,
    fastDelivery:true,
    image:".assets/WOMEN/Estee-Lauder-Pleasures-For-Women_.jpg",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    productName:"Zara-women-fruity-100ml (WOMEN)",
    qunatity:"100 ml",
    brand:"Zara",
    rating:"4.2",
    isRatingGood:true,
    originalPrice:"5000",
    sellingPrice:"999",
    discountOffer:"70% off",
    isSoldOut:true,
    fastDelivery:true,
    image:".assets/WOMEN/zara-fruity-women.jpg",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    productName:"zara-oriental-women- 100ml (WOMEN)",
    qunatity:"100 ml",
    brand:"Zara",
    rating:"4.8",
    isRatingGood:true,
    originalPrice:"5600",
    sellingPrice:"4009",
    discountOffer:"10% off",
    isSoldOut:false,
    fastDelivery:true,
    image:".assets/WOMEN/zara-oriental-women.jpg",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    productName:"zara-red-vanilla-women- 100ml (WOMEN)",
    qunatity:"100 ml",
    brand:"Zara",
    rating:"2.5",
    isRatingGood:false,
    originalPrice:"4000",
    sellingPrice:"2099",
    discountOffer:"50% off",
    isSoldOut:false,
    fastDelivery:false,
    image:".assets/WOMEN/zara-red-vanila-women.jpg",
    categoryName: "Women",
  },
];
